<?php

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class RedPortea {
    private $red_portena_options;

    public function __construct() {
        add_action( 'admin_menu', array( $this, 'red_portena_add_plugin_page' ) );
        add_action( 'admin_init', array( $this, 'red_portena_page_init' ) );
    }

    public function red_portena_add_plugin_page() {
        add_menu_page(
            'Red Porteña', // page_title
            'Red Porteña', // menu_title
            'manage_options', // capability
            'red-portena', // menu_slug
            array( $this, 'red_portena_create_admin_page' ), // function
            'dashicons-admin-generic', // icon_url
            2 // position
        );
    }

    public function red_portena_create_admin_page() {
        $this->red_portena_options = get_option( 'red_portena_option_name' ); ?>

        <div class="wrap">
            <h2>Red Porteña</h2>
            <p></p>
            <?php settings_errors(); ?>

            <form method="post" action="options.php">
                <?php
                settings_fields( 'red_portena_option_group' );
                do_settings_sections( 'red-portena-admin' );
                submit_button();
                ?>
            </form>
        </div>
    <?php }

    public function red_portena_page_init() {
        register_setting(
            'red_portena_option_group', // option_group
            'red_portena_option_name', // option_name
            array( $this, 'red_portena_sanitize' ) // sanitize_callback
        );

        add_settings_section(
            'red_portena_setting_section', // id
            'Settings', // title
            array( $this, 'red_portena_section_info' ), // callback
            'red-portena-admin' // page
        );

        add_settings_field(
            'instagram_0', // id
            'Instagram', // title
            array( $this, 'instagram_0_callback' ), // callback
            'red-portena-admin', // page
            'red_portena_setting_section' // section
        );

        add_settings_field(
            'facebook_1', // id
            'Facebook', // title
            array( $this, 'facebook_1_callback' ), // callback
            'red-portena-admin', // page
            'red_portena_setting_section' // section
        );
    }

    public function red_portena_sanitize($input) {
        $sanitary_values = array();
        if ( isset( $input['instagram_0'] ) ) {
            $sanitary_values['instagram_0'] = sanitize_text_field( $input['instagram_0'] );
        }

        if ( isset( $input['facebook_1'] ) ) {
            $sanitary_values['facebook_1'] = sanitize_text_field( $input['facebook_1'] );
        }

        return $sanitary_values;
    }

    public function red_portena_section_info() {

    }

    public function instagram_0_callback() {
        printf(
            '<input class="regular-text" type="text" name="red_portena_option_name[instagram_0]" id="instagram_0" value="%s">',
            isset( $this->red_portena_options['instagram_0'] ) ? esc_attr( $this->red_portena_options['instagram_0']) : ''
        );
    }

    public function facebook_1_callback() {
        printf(
            '<input class="regular-text" type="text" name="red_portena_option_name[facebook_1]" id="facebook_1" value="%s">',
            isset( $this->red_portena_options['facebook_1'] ) ? esc_attr( $this->red_portena_options['facebook_1']) : ''
        );
    }

}
if ( is_admin() )
    $red_portena = new RedPortea();

/*
 * Retrieve this value with:
 * $red_portena_options = get_option( 'red_portena_option_name' ); // Array of All Options
 * $instagram_0 = $red_portena_options['instagram_0']; // Instagram
 * $facebook_1 = $red_portena_options['facebook_1']; // Facebook
 */
